#!/gearlock/bin/bash

function apkmenu() {
	HEIGHT=0
	WIDTH=60
	CHOICE_HEIGHT=0
	BACKTITLE=$(gecpc "By Xtr" "+")
	TITLE="Apk installer"
	MENU="Install apk fast with pm, you can install all apks, enter level of subfolders to find apk 
	Third option is useful for apk that have broken x86 libs and you need to install for ARM"

	OPTIONS=(a "Install multiple apk from folder"
	         b "Install one apk"
             c "Install apk specifying abi")

	CHOICE=$(dialog --clear --cancel-label "Exit" \
	                --backtitle "$BACKTITLE" \
                    --title "$TITLE" \
	                --menu "$MENU" \
	                $HEIGHT $WIDTH $CHOICE_HEIGHT \
	                "${OPTIONS[@]}" \
	                2>&1 >/dev/tty)

case $CHOICE in
    	1)multi_apk;;
		2)one_apk;;
		3)abi_apk;;
}

abi_apk() {
r_action='apkmenu'

	file_action=\
	mkdir /mnt/"$filename"
	cd /mnt/"$filename"
	'7z x "$filepath"/"$filename" 
	lib_abi_list=($(ls ./lib))

	CHOICE=$(dialog --clear --cancel-label "Exit" \
	                --backtitle "$BACKTITLE" \
	                --menu  \
	                0 45 0 \
	                "${lib_abi_list[@]}" \
	                2>&1 >/dev/tty)
	
	'
	startdir=/sdcard
	filext='.apk'
	menutitle="Apk Selection Menu"
	source $filesdir/filebrowse.sh
}

multi_apk() {

}

one_apk() {
startdir=/sdcard
filext='.apk'
menutitle="APK Selection Menu"
file_action=\
'cp "$filepath/$filename" /data/local/tmp/
pm install "/data/local/tmp/$filename"'
r_action=apkmenu
source $filesdir/filebrowse.sh
}


apkmenu
