#!/gearlock/bin/bash


if [ -d /tmp ]; then
    tmp_dir=/tmp
else
    tmp_dir=/mnt
fi

function apkmenu() {
	HEIGHT=0
	WIDTH=60
	CHOICE_HEIGHT=6
	BACKTITLE=$(gecpc "By Xtr" "+")
	TITLE="Apk installer"
	MENU="Install apk fast with pm, you can install all apks, enter level of subfolders to find apk 
	Third option is useful for apk that have broken x86 libs and you need to install for ARM"

	OPTIONS=(a "Install multiple apk from folder"
	         b "Install one apk"
             c "Install apk specifying abi")

	CHOICE=$(dialog --clear --cancel-label "Exit" \
	                --backtitle "$BACKTITLE" \
                    --title "$TITLE" \
	                --menu "$MENU" \
	                $HEIGHT $WIDTH $CHOICE_HEIGHT \
	                "${OPTIONS[@]}" \
	                2>&1 >/dev/tty)

case $CHOICE in
    	a)source $filesdir/multi_apk;;
		b)one_apk;;
		c)abi_apk;;
		*)Loader;;
esac
	
}

abi_apk() {
	
r_action() {
	apkmenu
}

	file_action() {
	mkdir ${tmp_dir}/"$filename"
	cd ${tmp_dir}/"$filename"
	7z x "$filepath/$filename" 
	
	lib_abi_list=()
	while read -r line; do
    lib_abi_list+=($line $line)
	done < <( ls ./lib )
    
	rm -rf ${tmp_dir}/"$filename"

	MENU="Choose which architecture to install this apk
			The following abi are supported by your Android x86 
			$(getprop ro.product.cpu.abilist)"

	abi_choice=$(dialog --clear --cancel-label "Exit" \
	                --backtitle "$BACKTITLE" \
	                --menu "$MENU" \
	                0 60 4 \
	                ${lib_abi_list[@]} \
	                2>&1 >/dev/tty)

					[ $? -eq 1 ] && Loader
	
	cd "$filepath" 
	pm install --abi $abi_choice "$filename" && sleep 2
	
	
	}

	startdir=/sdcard
	filext='.apk'
	menutitle="Apk Selection Menu"
	source $filesdir/filebrowse.sh
}


one_apk() {
startdir=/sdcard
filext='.apk'
menutitle="APK Selection Menu"

file_action() {
cd "$filepath"
pm install "$filename"
}

r_action() {
	apkmenu
}

source $filesdir/filebrowse.sh
}

apkmenu
