#!/gearlock/bin/bash


if [ -d /tmp ]; then
    tmp_dir=/tmp
else
    tmp_dir=/mnt
fi

dialog --title "Warning" \
--ok-label "I read and understand" \
--msgbox "This doesnt extract archive to hard disk like other programs
It will extract files to RAM, so dont extract large archives which will fill your RAM and make the OS crash
Archives or gxp are extracted to $tmp_dir/<archive name> which is tmpfs ($tmp_dir/ is a folder in which files are stored in RAM, lost after reboot, in recovery mode /tmp)" \
13 60

startdir=/sdcard
filext=""
menutitle="Archive Selection Menu"


file_action() {
mkdir $tmp_dir/$filename
7z x "$filepath/$filename" -o$tmp_dir/$filename
}

r_action() {
    Loader
}

source $filesdir/filebrowse.sh 