#!/gearlock/bin/bash

	startdir=/sdcard
	filext='.apk'
	menutitle="Go to the folder in which apk are located and choose CurrentFolder"
#------------------------------------------------------------------------------
function Filebrowser()
{

    if [ -z $2 ] ; then
        
        dir_list=()
        while read -r line; do

            file=$(echo $line | awk '{ s = ""; for (i = 9; i <= NF; i++) s = s $i " "; print s }')
            size=$(echo $line | awk '{print $5}')
            dir_list+=("$file" $size)

        done < <( ls -lhp )
    else
        cd "$2"
        dir_list=()
        while read -r line; do

            file=$(echo $line | awk '{ s = ""; for (i = 9; i <= NF; i++) s = s $i " "; print s }')
            size=$(echo $line | awk '{print $5}')
            dir_list+=("$file" $size)

        done < <( ls -lhp )
    fi

	HEIGHT=20
	WIDTH=0
	CHOICE_HEIGHT=23
    curdir=$(pwd)
    if [ "$curdir" == "/" ] ; then  # Check if you are at root folder
        selection=$(dialog --title "$1" \
							  --ok-label Select \
                              --cancel-label Cancel \
							  --menu "$curdir" \
							  $HEIGHT $WIDTH $CHOICE_HEIGHT \
                              "${dir_list[@]}" 3>&1 1>&2 2>&3)
    else   # Not Root Dir so show ../ BACK Selection in Menu
        selection=$(dialog --title "$1" \
							  --ok-label Go \
							  --cancel-label Cancel \
							  --extra-button --extra-label CurrentFolder \
                              --menu "$curdir" \
							  $HEIGHT $WIDTH $CHOICE_HEIGHT \
                              '../' "go back One directory" "${dir_list[@]}" 3>&1 1>&2 2>&3)
    fi

    RET=$?
	if [ $RET = 3 ]; then
     
     dialog --yes-label "Current" --no-label "subfolders" --yesno "Selected folder: $curdir\n
     Do you want to install apk in current folder or find in subfolders also?" 10 45;
        case $? in 
            0)
             cd "$curdir"
                DIRS=( *.apk )
                
            ;;
            *)

            if (dialog --title "Do you want to specify maxdepth?" --yesno "You can specify maxdepth, so it will only find apk in that level of subfolders depth, choose no to find all" 9 55); then
	 user_input=$(dialog --title "Enter only a number" --inputbox \
		 	"Enter maxdepth, level of subfolders to find apk" 8 45 3>&2 2>&1 1>&3)

             i=${user_input//[^0-9]/1}
 
            DIRS=( $(find "$curdir" -maxdepth $i -iname '*.apk') ) 
            else
            DIRS=( $(find "$curdir" -iname '*.apk') ) 
	        
            fi
           
           
            ;;
        esac

        dialog --gauge "Installing apk" 9 55 < <(
   n=${#DIRS[*]}; 
   i=0
   for f in "${DIRS[@]}"
   do
   dir=$(dirname "$f")
     cd ${dir} 
      # calculate progress
      PCT=$(( 100*(++i)/n ))
      # update dialog box 
cat <<EOF
XXX
$PCT
$(pwd)
${f##*/}
XXX
EOF
  sleep 1
  pm install "${f##*/}"
   done
)




	fi

    if [ $RET -eq 1 ]; then  # Check if User Selected Cancel
       return 1	
    elif [ $RET -eq 0 ]; then
       if [[ -d "$selection" ]]; then  # Check if Directory Selected
          Filebrowser "$1" "$selection"
       elif [[ -f "$selection" ]]; then  # Check if File Selected
        
             dialog --msgbox "$selection\nYou Must go to a folder and Choose currentfolder" 7 45
             Filebrowser "$1" "$curdir"
         
       else
          # Could not detect a file or folder so Try Again
          dialog --title "ERROR: Selection Error" \
                 --msgbox "Error Changing to Path $selection" 7 45
				 Filebrowser "$1" "$curdir"
       fi
    fi
}


Filebrowser "$menutitle" "$startdir" 
apkmenu


