#!/gearlock/bin/bash

settings_list=( $(settings list $n | awk -F '=' '{print $1}') )

    HEIGHT=20
    WIDTH=45
    CHOICE_HEIGHT=20
MENU="select setting to modify"
CHOICE=$(dialog --clear --no-items --cancel-label "Exit" \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${settings_list[@]}" \
                2>&1 >/dev/tty)
