#!/gearlock/bin/bash

 HEIGHT=0
    WIDTH=45
    CHOICE_HEIGHT=0
MENU="select namespace"
n=$(dialog --clear --no-items --cancel-label "Exit" \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                system global secure \
                2>&1 >/dev/tty)

settings_list=( $(settings list $n | awk -F '=' '{print $1}') )

    
 HEIGHT=20
    WIDTH=45
    CHOICE_HEIGHT=20
    
MENU="select setting to modify"
CHOICE=$(dialog --clear --no-items --cancel-label "Exit" \
                --ok-label "Modify" \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${settings_list[@]}" \
                2>&1 >/dev/tty)

                current_value=$(settings list $n | grep $CHOICE | awk -F '=' '{print $2}')

                user_input=$(dialog --inputbox \
		 	"Key : $CHOICE
             current value : $current_value
             enter new value" 8 45 3>&2 2>&1 1>&3)

             settings put $n "${CHOICE}" "${user_input}" 
             Loader

    
    
