#!/gearlock/bin/bash
function shell_menu() {
	HEIGHT=0
	WIDTH=60
	CHOICE_HEIGHT=0
	BACKTITLE=$(gecpc "By Xtr" "+")
	TITLE="Install Custom Shells"
	MENU="Install Custom Shells"

	OPTIONS=(1 "zsh shell"
			 2 "fish shell"
	     	 3 "python shell")

	CHOICE=$(dialog --clear --cancel-label "Exit" \
	                --backtitle "$BACKTITLE" \
	                --menu "$MENU" \
	                $HEIGHT $WIDTH $CHOICE_HEIGHT \
	                "${OPTIONS[@]}" \
	                2>&1 >/dev/tty)

    case $CHOICE in
    	1)bash shells/zsh;;
		2)bash shells/fish;;
		3)bash shells/python;;
		*);;
	esac
}
shell_menu
# if (dialog --yesno "Do you want to install zsh shell in alt+f8 terminal?" 7 45); then
#   [ ! -f /data/data/com.termux/files/usr/bin/zsh ] && \
#   dialog --msgbox "Install zsh with termux first" 5 45 && Loader	
# fi

# if (dialog --yesno "Do you want to install python shell in alt+f8 terminal?" 7 45); then
#   [ ! -f /data/data/com.termux/files/usr/bin/python ] && \
#   dialog --msgbox "Install python with termux first" 5 45 && Loader

# fi


if [ -d /data/data/com.termux ]
then
mv -t "/data/data/com.termux/files/usr/bin/" $GHOME/.local/bin/*
rm -rf $GHOME/.local/bin
ln -s /data/data/com.termux/files/usr/bin $GHOME/.local/bin
dialog --msgbox "symlinked termux to gearlock, you can access termux from alt+f8 terminal, type fish or zsh python and enter in alt+f8 terminal" 7 45
fi