#!/gearlock/bin/bash
function shell_menu() {
	HEIGHT=0
	WIDTH=60
	CHOICE_HEIGHT=0
	BACKTITLE=$(gecpc "By Xtr" "+")
	TITLE="Install Custom Shells"
	MENU="Install Custom Shells"

	OPTIONS=(1 "Fish shell"
			 2 "Zsh shell"
	     	 3 "python shell")

	CHOICE=$(dialog --clear --cancel-label "Exit" \
	                --backtitle "$BACKTITLE" \
	                --menu "$MENU" \
	                $HEIGHT $WIDTH $CHOICE_HEIGHT \
	                "${OPTIONS[@]}" \
	                2>&1 >/dev/tty)

    case $CHOICE in
    	1)bash /system/ghome/dependencies/toolx/shells_folder/fish;;
		2)bash /system/ghome/dependencies/toolx/shells_folder/zsh;;
		3)bash /system/ghome/dependencies/toolx/shells_folder/python;;
		*);;
	esac
}
shell_menu