#!/gearlock/bin/bash
if (dialog --yesno "Do you want to install zsh shell in alt+f8 terminal?" 9 55); then
  [ ! -f /data/data/com.termux/files/usr/bin/zsh ] && \
  dialog --msgbox "Install zsh with termux first" 5 45 && exit	
fi

if (dialog --yesno "Do you want to install fish shell in alt+f8 terminal?" 9 55); then
  [ ! -f /data/data/com.termux/files/usr/bin/fish ] && \
  dialog --msgbox "Install fish shell with termux first" 5 45 && exit	

fi

if (dialog --yesno "Do you want to install python shell in alt+f8 terminal?" 9 55); then
  [ ! -f /data/data/com.termux/files/usr/bin/python ] && \
  dialog --msgbox "Install python with termux first" 5 45 && exit	

fi



mv -t "/data/data/com.termux/files/usr/bin/" $GHOME/.local/bin/*
rm -rf $GHOME/.local/bin
ln -s /data/data/com.termux/files/usr/bin $GHOME/.local/bin

dialog --msgbox "symlinked termux to gearlock, you can access termux from alt+f8 terminal, type fish or zsh python and enter in alt+f8 terminal" 7 45